### PR TITLE
Adding support for memcache host auto discovery

### PR DESCRIPTION
**Pull request by jbartek25**
First of all, my knowledge of Go is pretty limited so I ask you for patience and guidance :-). 

We have memcached set up in AWS ElastiCache and since the nodes can change over time, it's much more practical to use [the auto discovery feature](https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/AutoDiscovery.html), i.e. polling for a fresh list of hosts at preset interval.

The currently used [MC client lib](https://github.com/bradfitz/gomemcache) doesn't have support for auto discovery but there's [a Google fork of the original lib](https://github.com/google/gomemcache) that does. Unfortunately, there's unresolved  module name collision and until the fork gets merged into the master repo or until the fork's module name gets changed (there's a PR open for that since June 2020), I see with my limited Go knowledge 2 options:
1. Create a fork from Google's fork just to change the module name - doesn't sound good
2. Use go.mod `replace` command to override the old MC lib with the new one - that's what I did

Another thing, [instructions for the Google's MC lib](https://github.com/google/gomemcache) state the following:

> Remember to call Stop() on the discovery enabled client to stop the polling, else this can leak "go" methods.

I'm not sure if it's a big deal or not if Stop() isn't called but if this should be implemented, I assume the Stop command would be hooked on PBC shutdown logic after receiving SIGTERM or SIGINT. I see the logic which handles shutdown in server.go but I will ask your help in how to listen to shutdown in memcache.go probably through an interface exposing the shutdown listener to all backends.

### CODE REVIEW

**Comment by hhhjort** [comment]
I see a lot of updates in go.mod and go.sum. Was there a reason these other libraries updated, or did that just happen to occur while you were experimenting with solutions? 

For the `Stop()`, might it be suggesting to stop the polling after the desired memcache has been discovered? Your quote has note about leaking go methods, there should not be a concern about leaking anything on shutdown. But leaking during runtime, perhaps it continually runs the discovery routines until the stop, even if a memcache was found? (Perhaps to discover a new node in case the original one goes down?)

**Comment by jbartek25** [comment]
> Was there a reason these other libraries updated, or did that just happen to occur while you were experimenting with solutions?

The latter. I haven't specifically updated other libraries. 

> But leaking during runtime, perhaps it continually runs the discovery routines until the stop, even if a memcache was found? (Perhaps to discover a new node in case the original one goes down?)

It's desirable for the discovery routines to keep on running so that the PBC host doesn't have to be restarted in case a node gets added or removed. That's why the `poll_interval_seconds` parameter.

**Comment by hhhjort** [comment]
> > Was there a reason these other libraries updated, or did that just happen to occur while you were experimenting with solutions?
> 
> The latter. I haven't specifically updated other libraries.

Probably best to clean it up to limit the number of things changed. Updated libraries can creep in strange, hard to debug bugs because it is not obvious what has changed inside of them.

> > But leaking during runtime, perhaps it continually runs the discovery routines until the stop, even if a memcache was found? (Perhaps to discover a new node in case the original one goes down?)
> 
> It's desirable for the discovery routines to keep on running so that the PBC host doesn't have to be restarted in case a node gets added or removed. That's why the `poll_interval_seconds` parameter.

That makes sense.

**Comment by SyntaxNode** [comment]
@jbartek25 Could you please remove the ancillary library updates from this PR? We ask that those updates be done separately from feature work.

**Comment by SyntaxNode** [comment]
@jbartek25 Friendly ping. :)

**Comment by jbartek25** [comment]
sorry I've been busy. I'll get to this next week I hope.

**Comment by jbartek25** [comment]
> please remove the ancillary library updates from this PR

done

**Review by hhhjort — APPROVED** [review]
LGTM

**Review by guscarreon — APPROVED** [review]
LGTM, Thanks for your contribution @jbartek25

**Pull request merged**
